Repository Kong/gateway-operator, pull requests merged in 2022-09, with the labels that each got.

#278 Logging improvement
  controllers/controlplane_controller.go
  controllers/controlplane_controller_reconciler_utils.go
  controllers/dataplane_controller.go
  controllers/dataplane_controller_reconciler_utils.go
  controllers/gateway_controller.go
  controllers/utils.go
Labels: area/maintenance

#282 test: each test has its own environment
  test/e2e/environment_test.go
  test/e2e/utils_test.go
  test/e2e/webhook_test.go
Labels: area/tests, area/maintenance

#286 fix(ci): fix image testing workflow by using a lowercased github repository name
  .github/workflows/test-build.yaml
Labels: area/ci

#289 fix(ci): use lowercased repo in docker run invocation
  .github/workflows/test-build.yaml
Labels: area/ci

#246 fix(dataplane) always set default envs
  controllers/dataplane_controller.go
  internal/utils/dataplane/config.go
  test/integration/dataplane_test.go
Labels: bug, area/maintenance

#290 fix(ci): drop ghcr.io prefix from repo
  .github/workflows/test-build.yaml
  scripts/verify-version.sh
Labels: area/ci

#276 chore: put regular and redhat-certified bundles into separate dirs
  Makefile
  bundle/redhat-certified/bundle.Dockerfile
  bundle/redhat-certified/manifests/gateway-operator-admission_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/redhat-certified/manifests/gateway-operator-admission_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/redhat-certified/manifests/gateway-operator-admission_rbac.authorization.k8s.io_v1_role.yaml
  bundle/redhat-certified/manifests/gateway-operator-admission_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/redhat-certified/manifests/gateway-operator-admission_v1_serviceaccount.yaml
  bundle/redhat-certified/manifests/gateway-operator-controller-manager-metrics-service_v1_service.yaml
  bundle/redhat-certified/manifests/gateway-operator-manager-config_v1_configmap.yaml
  bundle/redhat-certified/manifests/gateway-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/redhat-certified/manifests/gateway-operator-validating-webhook_v1_service.yaml
  bundle/redhat-certified/manifests/gateway-operator.konghq.com_controlplanes.yaml
  bundle/redhat-certified/manifests/gateway-operator.konghq.com_dataplanes.yaml
  bundle/redhat-certified/manifests/gateway-operator.konghq.com_gatewayconfigurations.yaml
  bundle/redhat-certified/manifests/kong-gateway-operator.clusterserviceversion.yaml
  bundle/redhat-certified/metadata/annotations.yaml
  bundle/redhat-certified/tests/scorecard/config.yaml
  bundle/regular/bundle.Dockerfile
  bundle/regular/manifests/gateway-operator-admission_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/regular/manifests/gateway-operator-admission_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  bundle/regular/manifests/gateway-operator-admission_rbac.authorization.k8s.io_v1_role.yaml
  bundle/regular/manifests/gateway-operator-admission_rbac.authorization.k8s.io_v1_rolebinding.yaml
  bundle/regular/manifests/gateway-operator-admission_v1_serviceaccount.yaml
  bundle/regular/manifests/gateway-operator-controller-manager-metrics-service_v1_service.yaml
  bundle/regular/manifests/gateway-operator-manager-config_v1_configmap.yaml
  bundle/regular/manifests/gateway-operator-metrics-reader_rbac.authorization.k8s.io_v1_clusterrole.yaml
  bundle/regular/manifests/gateway-operator-validating-webhook_v1_service.yaml
  bundle/regular/manifests/gateway-operator.konghq.com_controlplanes.yaml
  bundle/regular/manifests/gateway-operator.konghq.com_dataplanes.yaml
  bundle/regular/manifests/gateway-operator.konghq.com_gatewayconfigurations.yaml
  bundle/regular/manifests/kong-gateway-operator.clusterserviceversion.yaml
  bundle/regular/metadata/annotations.yaml
  bundle/regular/tests/scorecard/config.yaml
Labels: area/build, area/operator-sdk, area/redhat-certification

#275 ci: add verification scripts
  .github/workflows/tests.yaml
  .golangci.yaml
  Makefile
  internal/utils/dataplane/config.go
  scripts/verify-diff.sh
  scripts/verify-repo.sh
  test/e2e/webhook_test.go
  test/integration/util_test.go
Labels: area/ci, area/build

#296 fix: increase memory limit and request for operator
  bundle/redhat-certified/manifests/kong-gateway-operator.clusterserviceversion.yaml
  bundle/regular/manifests/kong-gateway-operator.clusterserviceversion.yaml
  config/manager/manager.yaml
Labels: area/maintenance

#277 fix: add more metadata used in redhat certified operator
  bundle/redhat-certified/manifests/kong-gateway-operator.clusterserviceversion.yaml
  bundle/regular/manifests/kong-gateway-operator.clusterserviceversion.yaml
  config/manifests/bases/kong-gateway-operator.clusterserviceversion.yaml
Labels: area/redhat-certification

#269 logging e2e test
  internal/utils/test/generators.go
  test/e2e/environment_test.go
  test/e2e/operatorLogs_test.go
  test/e2e/webhook_test.go
  test/integration/gateway_test.go
Labels: area/tests
