Repository Kong/gateway-operator, pull requests merged in 2022-08, with the labels that each got.

#149 fix: add flag for cluster CA secret namespace and check if it's provided
  internal/manager/run.go
  main.go
  test/integration/suite_test.go
Labels: bug

#131 feat: add telemetry
  Makefile
  go.mod
  go.sum
  internal/manager/metadata/metadata.go
  internal/manager/run.go
  internal/telemetry/telemetry.go
  main.go
Labels: area/telemetry

#155 chore: don't send telemetry from dev builds
  internal/manager/run.go
  main.go
Labels: area/telemetry

#153 ci: add tests tags to linter config
  .golangci.yaml
  go.sum
  test/e2e/suite_test.go
  test/integration/asserts_test.go
  test/integration/controlplane_test.go
  test/integration/dataplane_test.go
  test/integration/gateway_test.go
  test/integration/ingress_test.go
  test/integration/predicates_test.go
  test/integration/suite_test.go
Labels: area/tests, area/ci

#157 docs: update KEP 1
  keps/0001-managed-gateways.md
Labels: area/kep

#184 feat: bump to new telemetry version framework
  go.mod
  go.sum
  internal/manager/run.go
  internal/telemetry/telemetry.go
Labels: area/telemetry

#207 fix: extend subresource readiness wait in tests
  test/integration/vars_test.go
Labels: area/tests, area/maintenance

#208 chore: update default tag of KIC to 2.5
  internal/consts/consts.go
Labels: area/maintenance

#210 chore: temporarily disable replacement tests
  test/integration/controlplane_test.go
  test/integration/gateway_test.go
  test/integration/vars_test.go
Labels: area/tests, area/maintenance

#198 tools: add opm to third_party go.mod
  Makefile
  third_party/go.mod
  third_party/go.sum
  third_party/opm.go
Labels: area/build

#205 chore(ci): add third_party dir to dependabot config
  .github/dependabot.yml
Labels: area/ci

#195 ci: add version info to container image
  Dockerfile
  Makefile
  main.go
Labels: area/ci, area/build

#227 fix(build): don't use temp dir for clien-gen
  Makefile
Labels: area/build

#228 docs: fix gateway wait command
  README.md
Labels: area/docs

#239 build: add makefile target for installing operator-sdk
  Makefile
Labels: area/build

#242 fix(crds): add annotations for manually added fields
  apis/v1alpha1/controlplane_types.go
  apis/v1alpha1/dataplane_types.go
  apis/v1alpha1/gatewayconfiguration_types.go
  config/crd/bases/gateway-operator.konghq.com_controlplanes.yaml
  config/crd/bases/gateway-operator.konghq.com_dataplanes.yaml
  config/crd/bases/gateway-operator.konghq.com_gatewayconfigurations.yaml
Labels: area/crds

#243 fix: remove networking.k8s.io DataPlane from PROJECT
  PROJECT
Labels: area/crds

#254 fix: bundle kustomize manifests generation
  Makefile
  PROJECT
  bundle/manifests/operator.clusterserviceversion.yaml
  config/manifests/bases/operator.clusterserviceversion.yaml
Labels: area/build, area/crds

#226 Improve status handling in reconciliation loops
  controllers/controlplane_controller.go
  controllers/controlplane_controller_reconciler_utils.go
  controllers/gateway_controller.go
  controllers/gateway_controller_reconciler_utils.go
Labels: area/maintenance

#237 docs - Kong enterprise in DBLess mode
  README.md
Labels: area/docs, area/enterprise

#253 fix: manual component upgrades/downgrades
  README.md
  controllers/controlplane_controller_reconciler_utils.go
  controllers/dataplane_controller_reconciler_utils.go
  controllers/utils.go
  controllers/utils_test.go
  test/integration/manual_upgrades_and_downgrades_test.go
Labels: bug

#255 fix: add kustomize samples for bundle generation
  bundle/manifests/operator.clusterserviceversion.yaml
  config/samples/controlplane.yaml
  config/samples/dataplane.yaml
  config/samples/gateway.yaml
  config/samples/kustomization.yaml
Labels: area/build, area/crds

#232 changing log structure for DEV mode
  controllers/controlplane_controller.go
  controllers/controlplane_controller_reconciler_utils.go
  controllers/dataplane_controller.go
  controllers/dataplane_controller_reconciler_utils.go
  controllers/gateway_controller.go
  controllers/utils.go
  internal/manager/controller_setup.go
  internal/manager/logging/encoding.go
  internal/manager/logging/levels.go
  internal/manager/run.go
Labels: area/maintenance

#263 build: use specific - apis/ - directory for controller-gen code generation
  Makefile
Labels: area/build

#265 chore: cleanup dockerfile
  Dockerfile
Labels: area/maintenance

#267 fix: remove RELATED_IMAGE_* from default config
  config/manager/manager.yaml
Labels: bug
